#!/bin/bash
set -e

# Script to generate minimal Atmos configuration at runtime
# Usage: ./generate-atmos-config.sh <workspace-name> [output-dir]
# 
# This script creates a minimal Atmos config that wraps existing Terraform workspaces
# without modifying the workspace structure. The config is generated at runtime only.

WORKSPACE="${1:?Workspace name required}"
OUTPUT_DIR="${2:-.}"

# Validate workspace exists
if [ ! -d "$WORKSPACE" ]; then
    echo "Error: Workspace directory not found: $WORKSPACE"
    exit 1
fi

# Create Atmos config directory structure
mkdir -p "$OUTPUT_DIR/atmos/conf"
mkdir -p "$OUTPUT_DIR/atmos/stacks"

# Generate atmos.yaml (root configuration)
cat > "$OUTPUT_DIR/atmos/conf/atmos.yaml" << 'EOF'
# Minimal Atmos configuration generated at runtime
# This wraps existing Terraform workspaces without modifying their structure

base_path: "."

components:
  terraform:
    base_path: "components/terraform"
    apply_auto_approve: false
    deploy_run_init: true
    init_run_terraform_fmt_check: false
    auto_generate_backend_file: false

stacks:
  base_path: "stacks"
  included_paths:
    - "**/*.yaml"
  excluded_paths:
    - "**/_*.yaml"

logs:
  level: "info"

# Atmos CLI configuration
cli:
  # Disable interactive prompts in CI/CD
  interactive: false
  # Use colors in output
  colors: true
EOF

# Generate stack configuration for the workspace
# The stack references the workspace directory as a Terraform component
STACK_NAME=$(echo "$WORKSPACE" | tr '/' '-')

cat > "$OUTPUT_DIR/atmos/stacks/${STACK_NAME}.yaml" << EOF
# Auto-generated stack configuration for workspace: $WORKSPACE

components:
  terraform:
    ${STACK_NAME}:
      metadata:
        component: "${STACK_NAME}"
        description: "Terraform workspace: $WORKSPACE"
      vars: {}
      backend:
        s3:
          encrypt: true
          dynamodb_table: "terraform-locks"
EOF

# Generate component configuration that references the workspace directory
mkdir -p "$OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}"

cat > "$OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}/main.tf" << EOF
# This component wraps the workspace directory: $WORKSPACE
# All Terraform code is in the workspace directory itself

# Import workspace variables and outputs
module "workspace" {
  source = "../../../${WORKSPACE}"
}

# Re-export workspace outputs
output "workspace_outputs" {
  description = "All outputs from the workspace"
  value       = module.workspace
}
EOF

# Generate terraform.tfvars.json for the component
cat > "$OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}/terraform.tfvars.json" << EOF
{
  "workspace_name": "${WORKSPACE}"
}
EOF

# Generate versions.tf for the component
cat > "$OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}/versions.tf" << EOF
terraform {
  required_version = ">= 1.0"
  
  # Backend configuration will be auto-generated by Atmos
  # or use the workspace's existing backend configuration
}
EOF

# Create a symlink or reference to the workspace's terraform files
# This allows Atmos to work with the existing workspace structure
cat > "$OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}/workspace.tf" << EOF
# Reference to workspace: $WORKSPACE
# The actual Terraform code is in the workspace directory

# This file serves as a bridge between Atmos and the workspace
# Atmos will execute terraform commands in this component directory
# which will use the workspace's configuration
EOF

echo "✅ Atmos configuration generated successfully"
echo "   Workspace: $WORKSPACE"
echo "   Stack: ${STACK_NAME}"
echo "   Config directory: $OUTPUT_DIR/atmos"
echo ""
echo "Generated files:"
echo "  - $OUTPUT_DIR/atmos/conf/atmos.yaml"
echo "  - $OUTPUT_DIR/atmos/stacks/${STACK_NAME}.yaml"
echo "  - $OUTPUT_DIR/atmos/components/terraform/${STACK_NAME}/"
