apiVersion: v1
kind: Secret
metadata:
  name: twistlock-secrets
  namespace: prisma-defender
type: Opaque
data:
  service-parameter: ${PRISMA_TWISTLOCK_SERVICE_PARAMETER}
  defender-ca.pem: ${PRISMA_TWISTLOCK_DEFENDER_CA}
  defender-client-cert.pem: ${PRISMA_TWISTLOCK_DEFENDER_CLIENT_CERT}
  defender-client-key.pem: ${PRISMA_TWISTLOCK_DEFENDER_CLIENT_KEY}
  admission-cert.pem: ${PRISMA_TWISTLOCK_ADMISSION_CERT}
  admission-key.pem: ${PRISMA_TWISTLOCK_ADMISSION_KEY}
