apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: ${KARPENTER_PROVISIONER}
  description: "General purpose NodePool for Apps"
spec:
  template:
    metadata:
      # Labels are arbitrary key-values that are applied to all nodes
      labels:
        intent: apps
    spec:
      nodeClassRef:
        name: ${KARPENTER_PROVISIONER}
      requirements:
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"] # Default region
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # refresh nodes every 30 days
