# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Configure ArgoCD Global Settings                                         │
# └──────────────────────────────────────────────────────────────────────────┘
controller:
  enableStatefulSet: true
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Configure ArgoCD ConfigMap                                               │
# └──────────────────────────────────────────────────────────────────────────┘
configs:
  params:
    server.insecure: true   # Fixes redirect issue - https://github.com/argoproj/argo-cd/issues/2953
  cm:
    create: true
    exec.enabled: true      # Enable terminal: https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Configure ArgoCD Server Settings                                         │
# └──────────────────────────────────────────────────────────────────────────┘
server:
  autoscaling:
    enabled: true
    minReplicas: 1
  resources:
    requests:
      cpu: 128m
      memory: 512Mi
  # Configure ArgoCD Ingress
  ingressGrpc:
    enabled: false # not needed
  ingress:
    enabled: false
  service:
    labels:
      app: argocd-server
    type: NodePort
  # Configure ArgoCD repoServer settings
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
    resources:
      requests:
        cpu: 128m
        memory: 64Mi

