apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: ${argoNamespace}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  project: ${argoProject}
  source:
    repoURL: ${repo}
    path: ${path}
    targetRevision: ${targetRevision}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: argoNamespace
          value: ${argoNamespace}
        - name: argoProject
          value: ${argoProject}
        - name: clusterDomain
          value: ${clusterDomain}
        - name: clusterName
          value: ${clusterName}
        - name: clusterServer
          value: ${clusterServer}
        - name: repoUrl
          value: ${repo}
        - name: storageClass
          value: ${storageClass}
        - name: targetRevision
          value: ${targetRevision}
  destination:
    server: ${clusterServer}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
