apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  project: default
  labels:
    app.kubernetes.io/managed-by: Helm
  source:
    repoURL: ${gitops_repo}
    path: ${gitops_services_path}
    targetRevision: ${gitops_branch}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: repoUrl
          value: ${gitops_repo}
        - name: path
          value: ${gitops_services_path}
        - name: targetRevision
          value: ${gitops_branch}
        - name: clusterName
          value: "${cluster_name}"
        - name: clusterEndpoint
          value: "${cluster_endpoint}"
        # Doppler Tokens for apps/envs
        - name: grafanaCreds.admin
          value: "${grafana_admin}"
        - name: grafanaCreds.pw
          value: "${grafana_pw}"
        - name: dbOperator.creds.user
          value: "${pg_user}"
        - name: mongoDBCreds.host
          value: "${mongodb_host}"
        - name: mongoDBCreds.user
          value: ${mongodb_user}
        - name: mongoDBCreds.pw
          value: ${mongodb_pw}
        - name: tapir.sso_clientID
          value: "${tapir_sso_client_id}"
        - name: tapir.sso_clientSecret
          value: "${tapir_sso_client_secret}"

  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
